### PR TITLE
Merge feat/add ci --> master

### PR DESCRIPTION
**Pull request by JLH993**
Added CI to kick off when PRs get opened to merge back to master. This will lint the python code being pushed out with flake8.

Eventually, this would be ideal to kick off after each commit, but we may hit limits during intial development and exceed the free usage for runners per month.

### CODE REVIEW

**Comment by Poolitzer** [comment]
@JLH993 What is about pre commit hooks?

**Comment by Poolitzer** [comment]
I am not sure I see the need for a separate requirements file, isnt poetry enough?

**Comment by d-Rickyy-b** [comment]
> I am not sure I see the need for a separate requirements file, isnt poetry enough?
tbh, I don't see the need of poetry at all+

**Comment by Poolitzer** [comment]
That sounds like a separate issue now :D

Or you mean for this context. for the tests?

**Comment by d-Rickyy-b** [comment]
separate issue and in consequence also here

**Pull request merged**
